name: platform_maps_flutter_google_android
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    implements: platform_maps_flutter
    platforms:
      android:
        dartPluginClass: PlatformMapsGoogleAndroid
        fileName: platform_maps_flutter_google.dart

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_android: ^2.7.0
  google_maps_flutter_platform_interface: ^2.6.0
  # replace by published version
  platform_maps_flutter_platform_interface:
    git:
      url: https://github.com/albert-heijn-technology/platform_maps_flutter
      path: packages/platform_maps_flutter_platform_interface
      ref: c7838abbbf9ef6c9347b68cde4b71563786aca5a

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

