name: platform_maps_flutter_apple
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    implements: platform_maps_flutter
    platforms:
      ios:
        dartPluginClass: PlatformMapsApple
        fileName: platform_maps_flutter_apple.dart

dependencies:
  flutter:
    sdk: flutter
  apple_maps_flutter: ^1.3.0
  # replace by published version
  platform_maps_flutter_platform_interface:
    git:
      url: https://github.com/albert-heijn-technology/platform_maps_flutter
      path: packages/platform_maps_flutter_platform_interface
      ref: c7838abbbf9ef6c9347b68cde4b71563786aca5a

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

