name: platform_maps_flutter_apple
description: "A new Flutter package project."
version: 1.0.0-beta
homepage:

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    implements: platform_maps_flutter
    platforms:
      ios:
        dartPluginClass: PlatformMapsApple
        fileName: platform_maps_flutter_apple.dart

dependencies:
  flutter:
    sdk: flutter
  apple_maps_flutter: ^1.3.0
  platform_maps_flutter_platform_interface: ^1.0.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

